### ISSUE TITLE
What are the units for wavelength?

### ISSUE THREAD

**Issue by sgbaird** [Stianpr20/MaXrd#3]
E.g. in BraggAngle. Angstroms? nm?

**Comment by stianpram** [comment]
All wavelength entries assume values in **angstroms**. Other units should either be converted first, or go in a `Quantity`, *e.g.*
```Mathematica
BraggAngle["Silicon", Quantity[150, "Picometers"], {1, 1, 1}]
```

I will clarify this in the documentation pages of the relevant functions. Thank you!
