### ISSUE TITLE
How to extract atomic positions from CrystalPlot?

### ISSUE THREAD

**Issue by sgbaird** [Stianpr20/MaXrd#4]
The way I'm doing it right now (with the correlated atoms) is:
```mathematica
\[ScriptCapitalC] = 
 CrystalPlot["GalliumArsenide", StructureSize -> {1, 1, 1}]
\[ScriptCapitalP] = {#} & /@ 
   Cases[\[ScriptCapitalC], _Sphere, \[Infinity]][[;; , 1]];
```
Displayed as:
```mathematica
TableForm[\[ScriptCapitalP]\[Transpose], 
 TableHeadings -> {None, GetElements["GalliumArsenide"]}]
```
Not sure if there's an easier built-in way.

**Comment by stianpram** [comment]
When the option `"StructureSize"` is used in `CrystalPlot`, the structure is only stored temporarily. In this case, I suggest “making” the crystal first, then  extract the coordinates.

Making the crystal:
```Mathematica
ExpandCrystal["GalliumArsenide", "NewLabel" -> "GaAs"](* Defaults to 1x1x1 *)
```
Plot it if you like with `CrystalPlot["GaAs"]`. Extract the columns with chemical element and coordinates:
```Mathematica
$CrystalData[["GaAs", "AtomData", All, {"Element", "FractionalCoordinates"}]]
```

Also, you can export the atomic position of a structure in a `"DISCUS"` format like this:
```Mathematica
ExportCrystalData["DISCUS", "GaAs", "~/Desktop/GaAs.txt"]
```

**Comment by sgbaird** [comment]
> Extract the columns with chemical element and coordinates:
> 
> ```mathematica
> $CrystalData[["GaAs", "AtomData", All, {"Element", "FractionalCoordinates"}]]
> ```
> 
> Also, you can export the atomic position of a structure in a `"DISCUS"` format like this:
> 
> ```mathematica
> ExportCrystalData["DISCUS", "GaAs", "~/Desktop/GaAs.txt"]
> ```
This only seems to work as intended if alpha == beta == gamma == 90 degrees
Otherwise the coordinates need to be transformed via the correct basis vectors.

For example,
```mathematica
R = GetCrystalMetric["GalliumArsenide", ToCartesian -> True];
coords = coords . R\[Transpose];
```

**Comment by stianpram** [comment]
Yes, crystallographic coordinates are used by default, but `CrystalPlot` objects contain Cartesian coordinates.

In the [latest commit](https://github.com/Stianpr20/MaXrd/tree/c6dec86b6e6e8b0f9236da0d2e1132e4c4076eb4), I've added the function `GetAtomCoordinates` which can extract coordinates of crystal (labels) and `CrystalPlot` objects. It has a Boolean option `"Cartesian"` for toggling the output coordinate system.
