### ISSUE TITLE
Maybe upload to a paclet repository?

### ISSUE THREAD

**Issue by sgbaird** [Stianpr20/MaXrd#8]

**Comment by stianpram** [comment]
Have not thought about it, thanks for the idea! I will see if I can submit it on [paclets.github.io](https://paclets.github.io/PacletServer/).

**Comment by sgbaird** [comment]
So awesome that it's paclet-installable now :D I should probably learn how to use this.

**Comment by stianpram** [comment]
That's good to hear! I think there was an overhaul of the documentation building tools in Mathematica 13. Now there is a palette called _Documentation Tools_ that you can use to make it, and an internal package called `PacletTools` for building it. See `Development > MaXrd_Build.nb`.

Before, I used the _Wolfram Workbench_ add-on in _Eclipse_
